name: Update VitaDash Feeds

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-feeds:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: tools
        run: npm install

      - name: Generate feeds
        working-directory: tools
        run: npm run update